apiVersion: v1
kind: Namespace
metadata:
  name: core-system
  labels:
    name: core-system
    tier: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    tier: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    name: security
    tier: security
